name: PHP Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          php-version: '7.4'
          configuration: phpunit.xml
