name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_DATABASE: dbname

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          configuration: tests/phpunit.xml


# jobs:
#   test:
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:5.6
#         env:
#           MYSQL_ROOT_PASSWORD: password
#           MYSQL_DATABASE: testing
#         ports:
#           - 33306:3306
#         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#     steps:
#       - name: PHPUnit Tests
#         uses: php-actions/phpunit@v9
#         with:
#           configuration: tests/phpunit.xml
#         env:
#           DB_PORT: 3306
#           DB_USERNAME: root
#           DB_PASSWORD: password
#           DB_DATABASE: testing
#           DB_HOST: mysql